export const menuItems = [
    { src: '/src/assets/images/avokado.jpg', caption: 'Avokado', type: 'breakfast' },
    { src: '/src/assets/images/breakfast.jpg', caption: 'Breakfast', type: 'breakfast' },
    { src: '/src/assets/images/breakfast2.jpg', caption: 'Breakfast', type: 'breakfast' },
    { src: '/src/assets/images/burger.jpg', caption: 'Burger', type: 'dinner' },
    { src: '/src/assets/images/drink.jpg', caption: 'Drink', type: 'drinks' },
    { src: '/src/assets/images/fish.jpg', caption: 'Fish', type: 'dinner' },
    { src: '/src/assets/images/fish2.jpg', caption: 'Fish', type: 'dinner' },
    { src: '/src/assets/images/fish3.jpg', caption: 'Fish', type: 'dinner' },
    { src: '/src/assets/images/fish4.jpg', caption: 'Fish', type: 'dinner' },
    { src: '/src/assets/images/fruits.jpg', caption: 'Fruits', type: 'breakfast' },
    { src: '/src/assets/images/fruits2.jpg', caption: 'Fruits', type: 'breakfast' },
    { src: '/src/assets/images/lunch.jpg', caption: 'Lunch', type: 'lunch' },
    { src: '/src/assets/images/macaruns.jpg', caption: 'Macaroons', type: 'dessert' },
    { src: '/src/assets/images/meat.jpg', caption: 'Meat', type: 'dinner' },
    { src: '/src/assets/images/meat2.jpg', caption: 'Meat', type: 'dinner' },
    { src: '/src/assets/images/omlet.jpg', caption: 'omlet', type: 'breakfast' },
    { src: '/src/assets/images/salad.jpg', caption: 'Salad', type: 'lunch' },
    { src: '/src/assets/images/seafood.jpg', caption: 'Seafood', type: 'dinner' },
    { src: '/src/assets/images/sushi.jpg', caption: 'Sushi', type: 'dinner' },
    { src: '/src/assets/images/sushi2.jpg', caption: 'Sushi', type: 'dinner' },
    { src: '/src/assets/images/sushi3.jpg', caption: 'Sushi', type: 'dinner' },
    { src: '/src/assets/images/taco.jpg', caption: 'Taco', type: 'lunch' },
    { src: '/src/assets/images/vegetables.jpg', caption: 'Vegetables', type: 'lunch' }
  ];